export const TABLE_NAMES = {
  REGIONS: 'regions',
  DISTRICTS: 'districts',
  COUNTRIES: 'countries',
  USERS: 'users',
  ADMINS: 'admins',
  PILGRIMS: 'pilgrims',
  OTP_CODES: 'otp_codes',
  OTP_SESSIONS: 'otp_sessions',
  REFRESH_TOKENS: 'refresh_tokens',
  AGENCIES: 'agencies',
  AGENCY_USERS: 'agency_users',
  LOCATIONS: 'locations',
  PILGRIM_AGENCY_HISTORY: 'pilgrim_agency_history',
  INVITATIONS: 'invitations',
  GROUPS: 'groups',
  GROUP_MEMBERS: 'group_members',
  ROOM_REQUESTS: 'room_requests',
  ROOM_REQUEST_MEMBERS: 'room_request_members',
  ROOMS: 'rooms',
  ROOM_MEMBERS: 'room_members',
  DUAS: 'duas',
} as const;
